package simpledb;

import java.util.*;

/**
 * The Join operator implements the relational join operation.
 */
public class Join extends Operator {

    private static final long serialVersionUID = 1L;
    
    private JoinPredicate p;
    private TupleDesc td;
    private OpIterator child1;
    private OpIterator child2;
    private int offset;

    /**
     * Constructor. Accepts two children to join and the predicate to join them
     * on
     * 
     * @param p
     *            The predicate to use to join the children
     * @param child1
     *            Iterator for the left(outer) relation to join
     * @param child2
     *            Iterator for the right(inner) relation to join
     */
    public Join(JoinPredicate p, OpIterator child1, OpIterator child2) {
        // some code goes here
        this.p = p;
        this.child1 = child1;
        this.child2 = child2;
        this.children.addAll(Arrays.asList(child1, child2));
        this.td = TupleDesc.merge(child1.getTupleDesc(), child2.getTupleDesc());
        this.offset = 0;
    }

    public JoinPredicate getJoinPredicate() {
        // some code goes here
        return p;
    }

    /**
     * @return
     *       the field name of join field1. Should be quantified by
     *       alias or table name.
     * */
    public String getJoinField1Name() {
        // some code goes here
        int field1 = p.getField1();
        TupleDesc td = child1.getTupleDesc();
        return td.getFieldName(field1);
    }

    /**
     * @return
     *       the field name of join field2. Should be quantified by
     *       alias or table name.
     * */
    public String getJoinField2Name() {
        // some code goes here
        int field2 = p.getField2();
        TupleDesc td = child2.getTupleDesc();
        return td.getFieldName(field2);
    }

    /**
     * @see simpledb.TupleDesc#merge(TupleDesc, TupleDesc) for possible
     *      implementation logic.
     */
    public TupleDesc getTupleDesc() {
        // some code goes here
        return td;
    }

    public void open() throws DbException, NoSuchElementException,
            TransactionAbortedException {
        // some code goes here
        super.open();
        child1.open();
        child2.open();
    }

    public void close() {
        // some code goes here
        super.close();
        child1.close();
        child2.close();
    }

    public void rewind() throws DbException, TransactionAbortedException {
        // some code goes here
        child1.rewind();
        child2.rewind();
        offset = 0;
    }

    /**
     * Returns the next tuple generated by the join, or null if there are no
     * more tuples. Logically, this is the next tuple in r1 cross r2 that
     * satisfies the join predicate. There are many possible implementations;
     * the simplest is a nested loops join.
     * <p>
     * Note that the tuples returned from this particular implementation of Join
     * are simply the concatenation of joining tuples from the left and right
     * relation. Therefore, if an equality predicate is used there will be two
     * copies of the join attribute in the results. (Removing such duplicate
     * columns can be done with an additional projection operator if needed.)
     * <p>
     * For example, if one tuple is {1,2,3} and the other tuple is {1,5,6},
     * joined on equality of the first column, then this returns {1,2,3,1,5,6}.
     * 
     * @return The next matching tuple.
     * @see JoinPredicate#filter
     */
    protected Tuple fetchNext() throws TransactionAbortedException, DbException {
        // some code goes here
        child1.rewind();
        for (int i = 0; i < offset; i++) {
            child1.next();
        }
        while (child1.hasNext()) {
            Tuple t1 = child1.next();
            Iterator<Field> it1 = t1.fields();
            while (child2.hasNext()) {
                Tuple t2 = child2.next();
                Iterator<Field> it2 = t2.fields();
                if (p.filter(t1, t2)) {
                    Tuple tuple = new Tuple(td);
                    int i = 0;
                    while (it1.hasNext()) {
                        tuple.setField(i, it1.next());
                        i++;
                    }
                    while (it2.hasNext()) {
                        tuple.setField(i, it2.next());
                        i++;
                    }
                    return tuple;
                }
            }
            child2.rewind();
            offset++;
        }
        return null;
    }

    @Override
    public OpIterator[] getChildren() {
        // some code goes here
        return (OpIterator[]) children.toArray();
    }

    @Override
    public void setChildren(OpIterator[] children) {
        // some code goes here
        this.children.addAll(Arrays.asList(children));
    }

}
